// we must import routers in express
const router = require("express").Router();

// import Student model
let student = require("../models/student");

//create router path and functionality add data into the database

//add student data into the database by teacher
router.route("/add").post((req, res) => {
  const name = req.body.name;
  const age = Number(req.body.age);
  const gender = req.body.gender;

  // now we create the object initialize the parameter values
  const newStudent = new student({
    name,
    age,
    gender,
  });

  newStudent
    .save()
    .then(() => {
      res.json("Studnt datat added successfully"); //send the response jason format into the fontend
    })
    .catch((err) => {
      console.log(err); //cthch the error and print error in the console
    });
});

// after see the data we need to get the data from the database
router.route("/").get((req, res) => {
  student
    .find()
    .then((student) => {
      res.json(student);
    })

    .catch((err) => {
      console.log(err);
    });
});

// update data in database, id id find the data and update id is automatic generated by mongodb ,this is unique id in document
router.route("/update/:id").put(async (req, res) => {
  // use the async function wait the process to complete another request

  // get user id
  let userId = req.params.id; // fetch user id

  const { name, age, gender } = req.body; // get data from frontend d structure

  // create object

  const UpdatedData = {
    name,
    age,
    gender,
  };
  const updateStudent = await student
    .findByIdAndUpdate(userId, UpdatedData) // find the id and update the data await function is used to wait for the backend promise to complete and then send the response , eka wadak karala iwara wenakam inawa ee wade karala iwarai kiayana kam eyaage wade karanna balagena
    .then(() => {
      res.status(200).send({ status: "student updated successfully" }); // respose send to the json format frontend details was updated successfully
    })
    .catch((err) => {
      console.log(err);
      res
        .status(500)
        .send({ status: "Error with updating data", error: err.message });
    });
});

// delete data in database, id id find the data and delete id is automatic generated by mongodb ,this is unique id in document
router.route("/delete/:id").delete(async (req, res) => {
  let userId = req.params.id; // id eka thibbama ati record ekk delete karanna
  await student
    .findByIdAndDelete(userId)
    .then(() => {
      res.status(200).send({ status: "student deleted successfully" });
    })
    .catch((err) => {
      console.log(err.message);
      res
        .status(500)
        .send({ status: "Error with delete data", error: err.massage });
    });
});

// get one user details

router.route("/get/:id").get(async (req, res) => {
  let userId = req.params.id;

  const oneuser = await student
    .findById(userId)
    .then((oneuser) => {
      res.status(200).send({
        status: "user fetch succussfully",
        user: oneuser /*pass as the object get user datails*/
      });
    })
    .catch((err) => {
      console.log(err.message);
      res
        .status(500)
        .send({ status: "Error with get user", error: err.massage });
    });
});
module.exports = router;
